name: Build Safari Web Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app

      # 🧭 Debug directory structure for clarity
      - name: Debug path
        run: |
          echo "Current directory:"
          pwd
          echo "Repo structure:"
          ls -R

      # 🧩 Validate manifest.json before conversion
      - name: Validate manifest.json
        run: |
          cd SafariWebExtension
          echo "Validating manifest.json..."
          if [ ! -f manifest.json ]; then
            echo "❌ Error: manifest.json not found in SafariWebExtension/"
            exit 1
          fi
          cat manifest.json | python3 -m json.tool > /dev/null
          echo "✅ manifest.json is valid JSON."

      # 🧱 Convert Safari Web Extension → Xcode project
      - name: Convert Safari Web Extension
        run: |
          mkdir -p build
          echo "Running converter on SafariWebExtension folder..."
          xcrun safari-web-extension-converter SafariWebExtension \
            --no-prompt \
            --project-location build \
            --bundle-identifier com.vavatheone.rightclicksafari \
            --app-name "RightClickSafari"

      # 🔍 List converter output
      - name: List converter output
        run: |
          echo "=== Converter output ==="
          ls -R build

      # 📄 Create development certificate
      - name: Create development certificate
        run: |
          security create-keychain -p github_actions build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p github_actions build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

      # ⚙️ Build iOS app (archive)
      - name: Build iOS app
        run: |
          cd build/*
          PROJECT_NAME=$(ls | grep .xcodeproj | sed 's/.xcodeproj//')
          echo "Detected project: $PROJECT_NAME"
          
          # Create archive
          xcodebuild archive \
            -project "$PROJECT_NAME.xcodeproj" \
            -scheme "$PROJECT_NAME (iOS)" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ../build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      # 📱 Create exportOptions.plist
      - name: Create exportOptions.plist
        run: |
          cat > build/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      # 📦 Export .ipa
      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist build/exportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      # 📋 List exported files
      - name: List exported files
        run: |
          echo "=== Exported files ==="
          ls -R build/export

      # ⬆️ Upload .ipa artifact
      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-ipa
          path: build/export
